export { default as HomePage } from './HomePage.vue'
export { default as SkillsPage } from './SkillsPage.vue'
export { default as ProjectsPage } from './ProjectsPage.vue'
export { default as ExperiencesPage } from './ExperiencesPage.vue'
export { default as AboutPage } from './AboutPage.vue'
