export { default as Home } from './Home.vue'
export { default as Skills } from './Skills.vue'
export { default as Projects } from './Projects.vue'
export { default as Experiences } from './Experiences.vue'
export { default as About } from './About.vue'
